#!/usr/bin/env bash
if [[ -z "$1" ]]; then
  echo
  echo "./scripts/build <size> [<size> [...]]  - build composable organizer for given sizes"
  echo
  echo "Example:"
  echo "  ./build 2,1,1 3,2,1 3,3,1"
  echo
  exit 1
fi

OUTPUT_DIR="output"
OUTPUT_EXT="stl"
mkdir -p $OUTPUT_DIR

for size in "$@"; do
  openscad -D '$fn=50' -D "size=[$size]" compartment.scad -o "$OUTPUT_DIR/compartment-$size.$OUTPUT_EXT"
  openscad -D '$fn=50' -D "size=[$size]" lid.scad -o "$OUTPUT_DIR/lid-$size.$OUTPUT_EXT"
done
