#!/usr/bin/env bash
if [[ -z "$1" ]]; then
  echo
  echo "./scripts/build <size> [<size> [...]]  - build composable organizer for given sizes"
  echo
  echo "Example:"
  echo "  ./build 2x1x1 3x2x1 3x3x1"
  echo
  exit 1
fi

OUTPUT_DIR="output"
OUTPUT_EXT="stl"
FILES=( compartment lid tray tray-lid )

git_sha=$((git rev-parse HEAD || echo "(none)") | cut -c 1-8)

mkdir -p $OUTPUT_DIR

for size in "$@"; do
  openscad_size="${size//x/,}"
  for file in "${FILES[@]}"; do
    echo "building $file with $size..." >&2
    cmd="openscad -D '\$fn=100' -D 'version_string=\"$git_sha\"' -D 'emboss_versions=true' -D 'size=[$openscad_size]' $file.scad -o \"$OUTPUT_DIR/$file-$size.$OUTPUT_EXT\"" 
    echo "$cmd" >&2
    echo "$cmd"
  done
done | parallel
