#!/usr/bin/env bash
if [[ -z "$1" ]]; then
  echo
  echo "./scripts/build <size> [<size> [...]]  - build composable organizer for given sizes"
  echo
  echo "Example:"
  echo "  ./build 2,1,1 3,2,1 3,3,1"
  echo
  exit 1
fi

OUTPUT_DIR="output"
OUTPUT_EXT="stl"
FILES=( compartment lid )
mkdir -p $OUTPUT_DIR

for size in "$@"; do
  for file in "$FILES"; do
    echo "building $file with $size..." >&2
    cmd="openscad -D '\$fn=100' -D "size=[$size]" $file.scad -o \"$OUTPUT_DIR/$file-$size.$OUTPUT_EXT\"" 
    echo "$cmd" >&2
    echo "$cmd"
  done
done | parallel
